name: get_server
version: 1.2.1
homepage: https://github.com/jonataslaw/get_server
description: A backend server (http and websocket) that makes it possible to program with Flutter syntax and reuse existing code
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  meta: ">=1.3.0 <2.0.0"
  mime: ^1.0.0
  jaguar_jwt: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
