name: get_server
description: A backend server that makes it possible to program with Flutter syntax and reuse existing code
version: 0.7.2
homepage: https://github.com/jonataslaw/get_server

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ">=1.1.1 <2.0.0"
  mime: ">=0.9.0 <1.0.0"
  http_server: ">=0.9.0 <1.0.0"
  get_instance: ">=3.10.2 <4.0.0"
  get_rx: ">=3.10.2 <4.0.0"
  jaguar_jwt: ^2.1.6
  

dev_dependencies:
  pedantic:
